import { CSSProperties } from "react";

const styles: Record<string, CSSProperties> = {
  root: {
    minHeight: "100vh",
    background: "#111",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    fontFamily: "'DM Sans', sans-serif",
  },
  card: {
    display: "flex",
    width: "100%",
    maxWidth: 860,
    minHeight: 560,
    background: "#1a1a1a",
    borderRadius: 20,
    overflow: "hidden",
    boxShadow: "0 32px 80px rgba(0,0,0,0.6)",
    border: "1px solid rgba(255,255,255,0.06)",
  },
  left: {
    flex: 1,
    padding: "32px 36px",
    display: "flex",
    flexDirection: "column",
    overflowY: "auto",
  },
  right: {
    width: 280,
    flexShrink: 0,
    background: "#141414",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  logo: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 28,
  },
  logoIcon: {
    width: 30,
    height: 30,
    background: "#222",
    border: "1.5px solid #ff2d2d",
    borderRadius: 7,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  logoText: {
    fontFamily: "'Syne', sans-serif",
    fontWeight: 800,
    fontSize: 13,
    letterSpacing: "0.12em",
    color: "#e0e0e0",
  },
  form: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  heading: {
    fontFamily: "'Syne', sans-serif",
    fontWeight: 700,
    fontSize: 26,
    color: "#f0f0f0",
    marginBottom: 4,
  },
  sub: {
    fontSize: 12.5,
    color: "#888",
    marginBottom: 20,
    lineHeight: 1.5,
  },
  label: {
    fontSize: 12,
    fontWeight: 500,
    color: "#aaa",
    marginBottom: 5,
    marginTop: 2,
  },
  input: {
    width: "100%",
    background: "#111",
    border: "1.5px solid #2e2e2e",
    borderRadius: 8,
    padding: "9px 12px",
    fontSize: 13,
    color: "#e0e0e0",
    marginBottom: 12,
    fontFamily: "'DM Sans', sans-serif",
  },
  row: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  checkRow: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    cursor: "pointer",
  },
  checkLabel: {
    fontSize: 12.5,
    color: "#aaa",
  },
  linkSmall: {
    fontSize: 12.5,
    color: "#aaa",
    textDecoration: "none",
  },
  primaryBtn: {
    width: "100%",
    background: "#ff2d2d",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "11px 0",
    fontSize: 14,
    fontWeight: 600,
    fontFamily: "'Syne', sans-serif",
    cursor: "pointer",
    letterSpacing: "0.04em",
  },
  switchText: {
    textAlign: "center",
    fontSize: 12.5,
    color: "#777",
    marginTop: 12,
  },
  dividerRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    margin: "16px 0 12px",
  },
  dividerLine: {
    flex: 1,
    height: 1,
    background: "#2a2a2a",
  },
  dividerText: {
    fontSize: 11.5,
    color: "#555",
    whiteSpace: "nowrap",
  },
  socialRow: {
    display: "flex",
    gap: 10,
    justifyContent: "center",
  },
  socialBtn: {
    flex: 1,
    background: "rgba(255,255,255,0.03)",
    border: "1.5px solid #2a2a2a",
    borderRadius: 8,
    padding: "9px 0",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  illustration: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    borderRadius: 16,
    margin: 12,
  },
  illustEmoji: {
    fontSize: 88,
    marginBottom: 16,
    filter: "drop-shadow(0 8px 24px rgba(0,0,0,0.15))",
  },
  illustDots: {
    display: "flex",
    gap: 6,
    marginBottom: 12,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "#ccc",
    opacity: 0.35,
    transition: "all 0.2s",
  },
  dotActive: {
    width: 18,
    borderRadius: 4,
    background: "#ff2d2d",
    opacity: 1,
  },
  illustCaption: {
    fontSize: 12,
    color: "#666",
    textAlign: "center",
    fontFamily: "'DM Sans', sans-serif",
  },
  grid2: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
  },
  eyeBtn: {
    position: "absolute",
    right: 10,
    top: "50%",
    transform: "translateY(-50%)",
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: 14,
    marginTop: -6,
  },
  backBtn: {
    fontSize: 12.5,
    color: "#888",
    padding: 0,
    textAlign: "left",
    fontFamily: "'DM Sans', sans-serif",
    background: "none",
    border: "none",
    cursor: "pointer",
  },
};

export default styles;